### ISSUE TITLE
Syntax: define builtin data types

### ISSUE THREAD

**Issue by fly-lang** [fly-lang/fly#11]
Define the main types for variables and constants to be used in the code considering to manage the common data types: integer and float numbers, boolean, strings, and array.
Moreover, it's important to expect:
1. integer with different number of bits, signed or unsigned
2. float with different number of bits, signed or unsigned
3. string representation, encoding, escape.
4. boolean representation
5. array representation

Think about it is better to include other built-in data types.

**Comment by marcoromagnolo** [comment]
These the main builtin data types:
`int` of 32bit
`float` of 32 bit
`bool` can be true or false
`string`
`array`

**Comment by fly-lang** [comment]
Created only int, float, bool
