### ISSUE TITLE
Syntax: define variable declaration

### ISSUE THREAD

**Issue by fly-lang** [fly-lang/fly#12]
How to declare a variable in two scopes:
- at the package level
- at the function level

## Package Var
A var can be accessed from all functions in that package. This var needs to be declared out the functions and not initialized, can be initialized only into a function.

## Function Var
A var can be accessed from only elements in the same function where declared.

**Comment by marcoromagnolo** [comment]
Package Var (like Global Var but visible only in package namespace) are declared in the same way as Function Var but in different positions.

Examples:
``int a``
``float b``
``string c``
``bool d``

**Comment by marcoromagnolo** [comment]
GlobalVar can be declared everywhere on top declarations by specifying:

- Visibility: 
  - Public visible out of the current namespace.
  - Private visible only into the current file.
  - Default visible only into the current namespace.
- Constant: modifiable or not at runtime.
- Type: the type of the variable.
- Identifier Name which identifies the var uniquely.
- Value: a default assigned value

Some examples:

`public int var1 = 1`
`float var2 = 2.0` (default visibility)
`private const bool var3 = false`
