### ISSUE TITLE
Syntax: define cycling blocks

### ISSUE THREAD

**Issue by fly-lang** [fly-lang/fly#16]
Define the cycling keywords and punctuators by considering the connected issue [Syntax: define the block of code delimiter](https://github.com/fly-lang/fly/issues/6).

- while, while-do, do-while
- for

**Comment by MattKotzbauer** [comment]
Java's system of "for(statement 1; statement 2; statement 3){function}" and "while(condition) {function}" feels like it has the most tangible structure to it. Python's "for __ in __" is nice and can let you dip straight into arrays without any extra labels, but I feel like it may be hard to incorporate into a combination of languages.

**Comment by marcoromagnolo** [comment]
> Java's system of "for(statement 1; statement 2; statement 3){function}" and "while(condition) {function}" feels like it has the most tangible structure to it. Python's "for __ in __" is nice and can let you dip straight into arrays without any extra labels, but I feel like it may be hard to incorporate into a combination of languages.

Yes, try to write an example of your code. Do not think about code implementation now, this phase is code free!
