### ISSUE TITLE
Add Global Vars feature

### ISSUE THREAD

**Issue by fly-lang** [fly-lang/fly#21]
Create global vars with default values:

``int a`` create a var with default value 0
``float b`` create b var with default value 0
``bool c`` create c var with default value false

Create global vars with assigned values:

``int a=1`` create a var with value 1
``float b=1.0`` create b var with value 1.0
``bool c=true`` create c var with value true

Global vars can be defined only after package definition:

```
package packageA

int a=1

```

**Comment by marcoromagnolo** [comment]
Resolved with pull request: #22
