### ISSUE TITLE
Add package feature

### ISSUE THREAD

**Issue by fly-lang** [fly-lang/fly#4]
Related to: [Syntax: define package, imports and namespace](https://github.com/fly-lang/fly/issues/10)

## Implements module features in order to prepare the logic for packages
A single source file: 
- have to belongs to only one package,
- can have the same package of more other source files

More source files:
- can be grouped into one package as a logical group
- of the same package raises an error if own same variables, constants, functions.

Add `package` keywords to:
https://github.com/fly-lang/fly/blob/35589d51dee40e8f84948d61ea8e6f06a881e948/include/Basic/TokenKinds.def#L113

**Comment by marcoromagnolo** [comment]
Use as the first declaration in the file:

``package "packageA"``

**Comment by marcoromagnolo** [comment]
Declaration of the package is a definition of a namespoace and can be made with:
`namespace "packageA"` 

This namespace can be imported with:
`import "packageA"` 

#22
