### ISSUE TITLE
Syntax: define the block of code delimiter

### ISSUE THREAD

**Issue by fly-lang** [fly-lang/fly#6]
Each programming languages use a different kind of block delimiter, for functions and statements defining:
 - {} used in C/C++, Java, Go, PHP, C#, Swift, Rust ...
 - tab and spaces used in Python, Haskell 
 - Special keywords like Begin/End used in Pascal, Delphi, ML 
 - A mix of brace, spaces, and keywords like in Ruby

Chose the Fly solution for maintaining code readability and ease of use.

**Comment by marcoromagnolo** [comment]
I think that the use of the braces is consolidated in most of the programming languages used until now.
But I know also that Python which is one of the most popular uses spaces, though there is who prefer Python with brace http://python-with-braces.appspot.com/ and https://github.com/mathialo/bython
Moreover with braces you can define multiple statements in one row without change syntax with additional delimiters:
https://stackoverflow.com/questions/6167127/how-to-put-multiple-statements-in-one-line
