### ISSUE TITLE
Syntax: define statement separator or terminator

### ISSUE THREAD

**Issue by fly-lang** [fly-lang/fly#9]
How to demarcate boundaries between two separate statements?
Define statement terminator for using to demarcate the end of an individual statement and its implicit behavior:

- C/C++, Java: uses a semicolon
- Javascript: use an implicit semicolon if not present in the code
- Go: not use semicolons but the compiler inserts them.
- Python: newline terminated

**Comment by marcoromagnolo** [comment]
Go: **not use semicolons** but the compiler inserts them

This is the best behavior!
